(setq *features* (cons 'uranus *features*))
(load "decl.lisp")
(load "defs.lisp")
(load "lib.lisp")
(load "amuse.lisp")
(load "systempred.lisp")
(load "trace.lisp")
(load "kernel.lisp")
(load "stepper.lisp")
(load "lib.lisp")
(load "lispfunctions.lisp")
(load "td.lisp")
(load "readin.lisp")

